[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x23c4b391b508a9176512f6f00fe9525a647cef3271b6e91d671088d0a9768edd'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]